### ISSUE TITLE
Parameter name verbosity

### ISSUE THREAD

**Issue by mobiletoly** [Kotlin/KEEP#118]
I found that most of the time when I specify parameter name it is the same as variable name. E.g.

```
val searchCriteria = SearchCriteria(offset = 0, limit = 10)
val params = mapOf("coolParam" to "coolValue")
val listings = listingService.getListings(searchCriteria = searchCriteria, params = params, flag = 1)
```

would be great to have a short notation when variable name and parameter name are the same, e.g.
```
val searchCriteria = SearchCriteria(offset = 0, limit = 10)
val params = mapOf("coolParam" to "coolValue")
val listings = listingService.getListings(#searchCriteria, #params, flag = 1)
```

**Comment by voddan** [comment]
listingService.getListings(searchCriteria = searchCriteria, params = params, flag = 1)

Why do you specify named parameters here to begin with? Their names do not add value (as you rightly mentioned) and if `flag` is the last parameter, you can drop them: `listingService.getListings(searchCriteria, params, flag = 1)`

**Comment by mobiletoly** [comment]
I specified names parameters, because they are great. What if you have a function with 3 string parameters (c, b, a). And then later you decided that you want to reorder parameters as (a, b, c) and you do it your function. Compiler is not going to complain. But now suddenly you code is not working as expected. Also what do you prefer:

addPerson("John", "Doe", 60)

or

addPerson(firstName="John", lastName="Doe", age=50)

at least you are clearly stating that 60 is your age, not your weight in kilos. And you don't have to guess which parameter is first name and which is last name.

**Comment by voddan** [comment]
@mobiletoly 

I think there is a big difference in this situation when you are using string constants and when you are using well-named variables:

    addPerson(firstName = "John", lastName = "Doe", age = 60)  // Thank you for specifying the named arguments!

    addPerson(firstName = firstName, lastName = lastName, age = age)  // Em, what's the point?

    addPerson(firstName, lastName, age)  // That's totally clear

As far as I understand your proposal, you want to improve the second case (see above) while arguing for the first case, which is very different. 

> And then later you decided that you want to reorder parameters as (a, b, c) in your function declaration. Compiler is not going to complain.

As for the reordering, the compiler is not going to complain ether way, so your best bet is InteliJ's reorder parameters refactoring which takes care of it automatically.

**Comment by voddan** [comment]
> that is not totally clear if you decide to refactor your function and decided that now you want to declare this function as
>
>>addPerson(lastName: String, firstName: String, age: Int)

Not sure I follow. If I use the IJ refactoring for that, it swaps the parameters accordingly in all places of usage. It's limitations are exactly the same as with the proposed language feature.

**Comment by mobiletoly** [comment]
> @voddan
> 
> > so your best bet is InteliJ's reorder parameters refactoring which takes care of it automatically
> 
> This feature works only for your own code in the current project.

Exactly. And even for your own code it is not going to work if you don't explicitly specify parameter names.

**Comment by hannespernpeintner** [comment]
> How is IntelliJ going to "swap parameters" if they are both String and are not named.

I think IJ searches for all occurrences and swaps parameters by position, regardless of how they are named. If you change foo(a: String, b: String) to foo(b: String, a: String), every call to foo will get its parameters swapped. This ignores named parameters. That works... but I think this tooling feature is totally unrelated to this proposal and to the Kotlin language, because named parameters are not positional, which means they are more robust in regards to method signature changes, compared to regular parameter passing.

The reason why we don't always pass params position-neutral with named params is the verbosity where it doesn't add value (besides being position-neutral...). Which is why I like this proposal very much. It also comes in very handy when using interface implementation by delegation. I could post another example here, if you folks like to :)

**Comment by mobiletoly** [comment]
Yes please, post another example. I like my proposal as well (what a surprise :) so more use cases we have - more helpful.

**Comment by hannespernpeintner** [comment]
I have an example from graphics/game development. There is a public texture interface and a simple implementation for each gpu backend, for example OpenGl:

```
interface Texture {
    val dimension: Dimension
    val target: TextureTarget
    val internalFormat: Format
    var handle: Long
    val identifier: String
    val textureFilterConfig: FilterConfig
    var uploadState: UploadState
}
class OpenGlTexture(
    val textureService: TextureService,
    override val dimension: Dimension,
    override val internalFormat: Format = if(COMPRESSED_TEXTURES) COMPRESSED else UNCOMPRESSED
    override val target: TextureTarget = TEXTURE_2D,
    override val handle: Long = generateHandle(),
    override val identifier: String = "OpenGlTexture-$handle",
    override val textureFilterConfig: FilterConfig = LINEAR,
    override var uploadState: UploadState = Uploaded
): Texture
```

This works perfectly, The OpenGlTexture implementation has some sensible default values, for example the state is set to uploaded, because no texture data is given and the texture is only used as render target and the identifier is based on the handle.
One of the most important applications for textures is loading them from files, images. An implementation is

```
class PathBasedOpenGlTexture(
    textureService: TextureService,
    path: String,
    dimension: Dimension,
    target: TextureTarget = TEXTURE_2D,
    textureFilterConfig: FilterConfig = MIPMAPPED,
    uploadState = NOT_UPLOADED,
    val backingTexture: OpenGlTexture = OpenGlTexture(textureService = textureService, dimension = dimension, target = target, identifier = path, textureFilterConfig = textureFilterConfig)
):Texture by backingTexture
```

This is similar to how I implemented it (it is simplified a bit). The class OpenGlTexture is implemented in a library and probably published for everyone because it is a handy layer over naked OpenGl textures, whilst the PathBasedOpenGlTexture is in my application and not published. This means I don't want to arbitrarily change the order of OpenGlTexture's parameters, only so that one can omit parameters at the end of the signature. This also means that passing paramters to the backingTexture is not simple, because for example the internalFormat should only be passed if really necessary. It would be nice to change
```
val backingTexture: OpenGlTexture = OpenGlTexture(textureService = textureService, dimension = dimension, target = target, identifier = path, textureFilterConfig = textureFilterConfig
```
to
```
val backingTexture: OpenGlTexture = OpenGlTexture(#textureService, #dimension, #target, identifier = path, #textureFilterConfig
```

The same applies when using factory methods instead of delegation, because there would be a lot of duplicated parameter names as well.

This got a bit long - Is this a good example? If not, I am willed to clear this post for clarity :)

**Comment by aananko** [comment]
We should probably separate readability from safety here.
Given
```
val name = "John"
val surname = "Doe"

fun doSomething(name: String, surname: String) { ... }
```
consider
```
doSomething(name, surname)
```
vs
```
doSomething(name=name, surname=surname)
```
The former is short and readable still being self-documenting. The latter adds one additional thing - safety (sacrifising some readablility), eliminating the risk of accidently messing up the argument order. IDE can help to minimize the risk, but can't eliminate it completely. Compiler can.

One way to achieve similar or even wider safety is to rely on type system:
```
data class Name(val value: String)
data class Surname(val value: String)

val name = Name("John")
val surname = Surname("Doe")

fun doSomething(name: Name, surname: Surname) { ... }

doSomething(name, surname)
```
This approach has some disadvantages over named arguments - more boilerplate (type definition, value unpacking), probably less performance (as Value Classes are not in Kotlin for now).  And one advantage - its safety can span all over the design, not just one function. Maybe this is not only and advantage but an indication of slightly different use case.

So I would argue in favor of this feature - some additional safety without any performance cost, with minimal language spec pollution and probably relatively easy implementation.

Still, I would suggest changing the proposed syntax a bit. Equal sign `=` is probably better suited here than `#`:
```
doSomething(=name, =surname)
```
This looks more intuitive (at least for me), and does not break the language grammar (as far as I can see). And also this variant does not introduce any new symbols to the language spec, which seems kind of avoided by Kotlin designers.

**Comment by elizarov** [comment]
Thanks. I've moved this issue to the Kotlin issue tracker. Please, vote and continue the discussion there -> https://youtrack.jetbrains.com/issue/KT-44072
