### ISSUE TITLE
Double question mark (??) and double Elvis (??:) operator; exception-safe operators

### ISSUE THREAD

**Issue by Spheniscine** [Kotlin/KEEP#178]
**Proposal:**
`expression??` expands to `try { expression } catch (e: Exception) { null }`
`expression ??: defVal` expands to `try { expression } catch (e: Exception) { defVal }`

**Rationale:**
One can almost think of this as the opposite of the double-bang (!!) operator. This might be a bit controversial, but I have, as one could say, "learned to love the double-bang"; it's a great shorthand for all those lifecycle-dependent properties, especially in Android development. Defining, e.g., 
```
val BaseFragment.ctx = context!!
val BaseFragment.act = activity as BaseActivity /* unsafe cast */
```
allows you to grab the context, and cast the activity to your BaseActivity class (including any added functionality from your BaseActivity or e.g. from AppCompatActivity) whenever you're sure that the context is not null, i.e. the fragment is currently attached to an activity, and you're sure you only attach your fragment to instances of BaseActivity, without a ton of ?.let{} all over the place. Additionally, Kotlin NPE's are in a way "better" than Java NPEs, since they are fail-fast and checked in-situ, rather than potentially causing a problem 20 lines later in a completely different block of code; indeed, one might prefer this fail-fast behavior over the potentially confusing behavior of simply doing nothing in the case where the expression fails, and possibly causing an illegal state of the application.

However, occasionally, you do need to use these expressions safely, like for example in a detach() function: you don't want the app to crash because you accidentally called it twice. As such, one can use ?? and ??: to access these expressions safely.

Even if you hate the double-bang and avoid it at all costs, these operators can prove very useful for expressions that throw exceptions, if you don't care about the type or content of those exceptions. Indeed, I believe these operators can completely obviate the need for the "xOrNull" functions from the standard library (e.g. `list[20]??` instead of `list.getOrNull(20)`), and partially obviate the need for "xOrElse" functions if you don't care to use the index or passed value (e.g. `list[20] ??: 0` instead of `list.getOrElse(20) { 0 }`)

**Workaround:**
Currently the best way to emulate these operators would be to define the inline functions `<T> orNull(expression: () -> T): T?` and `<T> orElse(defValue: T, expression: () -> T): T`

**Comment by fvasco** [comment]
`runCatching` address your issue without special support.

**Comment by DanySK** [comment]
Uhm... Personally I think that the availability of such operators would make it very, very easy to abuse exceptions as flow control mechanisms. Which is bad for understandability and very bad for performance.
The example with the list is emblematic. You should use a method which checks the access correctness, not accessing, populating a stacktrace, then throwing it all away.

**Comment by zunjae** [comment]
I'm a huge fan of creating apps that are maintainable. As such, I disagree with this proposal. Please do not encourage the behavior where issues are ignored, even if you don't care about them!

**Comment by domazey** [comment]
As I see many disagree with the concept, but how is this different than `?.` operator? It's the same - you  just ignore result if there is null, or handle it within `?:` operator. The arguments above suggest that this is not maintainable. Actually it's much more maintainable than consecutive `?.` operators calls, because at least we will know what caused error, which is not the case for `?.`, because it only suggests that at some point there was null, thus flow is stopped, if the `??:` operator is implemented correctly into the language, providing the exception that caused the error, it's pretty maintainable in my eyes, and much more pretty **for** the eyes.

The problem is that many programmers have to work with terrible libraries that can throw errors at any point, and `try catching` everything is tiring and ugly.

As for `runCatching`, look at this:
```kotlin
val result: Int = runCatching { someMethod() }.getOrNull() ?: 42
```
VS
```kotlin
val result: Int = try { someMethod() } catch(ex: Throwable) { 42 }
```
VS
```kotlin
val result: Int = someMethod() ??: 42
```

If it is easy to abuse feature, what about `!!` operator? It's in the core of the language, and is abused incorrectly by large part of Kotlin programmers. I hope you see my point.

**Comment by DanySK** [comment]
You fail at grasping what exceptions are and why they are there. Kotlin `null` values are actually reminiscent of functional `Option`s, namely nullable values may or may not hold a value. If they do computation progresses, otherwise halts.

Exceptions are designed for **exceptional** situations, not for normal control flow. The `??:` operator would suggest people that's ok doing what you did there, and in general **it is not**. It is a very bad code smell, and [it leads to performance issues](https://shipilev.net/blog/2014/exceptional-performance/).
IMHO `runCatching` as it is is a bad idea as well, as it should actually have returned an `Either<E,R>`. Losing stacktrace information is *bad*. I can only see the following cases:
1. You do not need stacktrace information, hence you should not use exceptions, you are abusing of them for control flow
2. You do need stacktrace information, then you cannot use `runCatchin` or `??:`
3. You are relying on badly designed code off your control, which is hopefully not a frequent situation, and it is something that you can deal with from time to time `runCatching`.

**Comment by domazey** [comment]
I'm not saying that exception system should be abused. I'm not trying to reinvent what's craved in stone. I'm just looking for better syntax for what is already present and verbose. Maybe `someMethod() ??: 42` is a bad example. I am fine with forced error handling, so be it
```kotlin
val result: Int = someMethod() ??: let { ex -> /* handle exception or 42 if lazy */}
```
Above `let` is placeholder, could be whatever. I hope that it clears your 1-3 points.

**Comment by DanySK** [comment]
I don't see how
```kotlin
val result: Int = someMethod() ??: let { ex ->  /* handling*/ }
```
improves over
```kotlin
val result: Int = try { someMethod() } catch(ex: Exception) { /* handling*/ }
```

Do you really thing is an improvement worth a new operator? If so, I respect your opinion, but I firmly disagree.

**Comment by gildor** [comment]
> and is abused incorrectly by large part of Kotlin programmers
`!!` is not abused, it will throw an exception with proper stack trace, it just means that there is some bug, and it's exactly why it's useful and usage is not abuse, it can be indeed replaced with some other Kotlin features (like with contracts we removed quite a lot of `!!` from our codebase, `!!` just not needed in some cases anymore), but it doesn't swallow any exceptions

**Comment by larssn** [comment]
I wanna outline that a lot of languages have adopted the null coalescing operator `??`, and that in itself is a great idea.

However I agree that it should **NOT** expand into the exception catching expression in the OP, reasons for which are nicely outline by Dany.

**Comment by elizarov** [comment]
While it definitely looks appealing, adding special symbols to the language has an extremely high cost in terms of learning, especially since there is no precedent for such a syntax in any of the popular languages so it is not familiar to anyone. We discussed internally the direction of adding some kind of special exception-handling sytax in the Kotlin team and came to the consensus that it is a no-go. 

In this particular case, we already have a library solution for dealing with exception, e.g. a proposed `expression??` is effective `runCatch { expression }.getOrNull()`, which is more verbose, but more explicit at the same time.
