### ISSUE TITLE
unreachable()

### ISSUE THREAD

**Issue by ligi** [Kotlin/KEEP#204]
### Problem Description

Currently `when` is only exhaustive when it is used as an expression. It would be great to get a language feature so we can also have `when` to be exhaustive when `when` is not used as an expression. This can help to indicate potential bugs at compile time e.g. when you add a new subclass to a sealed class and forgot to handle this new case it in some `when` usage.

There are workarounds one can currently use to do this like:

```kotlin
when(foo) {
 ..
}.let {}
```

but IMHO this is not really readable and looks bad.
Or:

```kotlin
val Any.exhausive : Unit
    get() = Unit

when (foo) {
..
}.exhaustive
```

which is IMHO better but has the drawback that you get this exhaustive in code completion for ANYthing - not only for when statements.

IMHO the best solution I found so far is:

```kotlin
object Do {
    inline infix fun<reified T> exhaustive(any: T?) = any
}
Do exhaustive when (foo) {
...
}
```

Would still love to see this as a language feature.

## Syntax / Implementation options

there are multiple options - e.g.:

```kotlin
when(foo,exhaustive=true) {
 ...
}
```

or

```kotlin
when(foo) {
 ...
 !else
}
```

or

```kotlin
exhaustiveWhen(foo) {
 ...
}
```

I would be happy with any of these 3 options and if need to choose would pick option 2
Just for completeness: another option would be to make it the default. Some people would like it (see links below) - but a) would this be a breaking change and b) core Kotlin developers do not like this option and having `when` non exhaustive by default is a design choice. So I think this is off the table.

### Links

* https://discuss.kotlinlang.org/t/algebraic-data-types-are-not-exhaustive/1857
* https://discuss.kotlinlang.org/t/allow-in-exhaustive-when/7823
* https://proandroiddev.com/til-when-is-when-exhaustive-31d69f630a8b
* https://www.reddit.com/r/Kotlin/comments/bzsiw3/force_exhaustive_whenstatement_sealed_classes/
* https://stackoverflow.com/questions/38169933/force-compilation-error-with-sealed-classes/50642387#50642387

**Comment by quickstep24** [comment]
How about a more general approach, having an intrinsic function (or a keyword) that creates a compiler error if it is reachable. Let me just call it `unreachable()` for discussion. It would have a lot of use cases.

Exhaustive when:
```
when (foo) {
   ...
   else -> unreachable()
}
```

Prevent accidental escape:
```
while (true) {
   ...  // check that there is no break in this code
}
unreachable()
```

Compile time exclusion:
```
if (false) {
    unreachable()
    ...   // some temporarily excluded code
}
```

Instead of a function, it could be the keyword combination `is unreachable` (`is` = existing hard keyword, `unreachable` = new soft keyword).

**Comment by ligi** [comment]
I like the idea of `unreachable` as it is very expressive and generalized. Thanks for the suggestion - just changed the title to it and think this is the best idea for this problem currently. Really hope we will see it in future kotlin versions.

**Comment by drothmaler** [comment]
Hm... Why not reuse [`Nothing`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-nothing.html) instead?

**Comment by ligi** [comment]
can you elaborate how you would use Nothing here? Nothing is a type - but as far as I see we would need a keyword/statement to solve the problem.

**Comment by drothmaler** [comment]
Well Kotlin usually prefers general purpose solutions, instead of new constructs for everything. So I would prefer to reuse something existing instead of adding something new.
Let me just cite the linked documentation for `Nothing`: 

> Nothing has no instances. **You can use Nothing to represent "a value that never exists"**: for example, if a function has the return type of Nothing, it means that it never returns (always throws an exception).

So (to me) it seems to mean exactly what you want/need.
The only downside is the name. I think something like "Never" would have been better. But it's probably a bit late for that.

**Comment by ligi** [comment]
Never would IMHO be a bad name for a type - hence I think Nothing is good how it is. But I still think (even though I like the idea of general purpose solutions) your Idea would mix types with statements. And this feels less like a general purpose solution as a  "eierlegende Wollmilchsau" (egg-laying, milk-bearing woolly sow)

**Comment by elizarov** [comment]
Thanks a lot for all the ideas and a healthy discussion.  I'm closing this issue since it does not constitute a specific design proposal (see https://github.com/Kotlin/KEEP/blob/master/README.md). Please, follow the discussion of the corresponding issue at https://youtrack.jetbrains.com/issue/KT-12380. It will track this particular problem of "when exhaustiveness" until a concrete proposal is worked out.

**Comment by ligi** [comment]
There is now: https://github.com/cashapp/exhaustive that works for me
