### ISSUE TITLE
Denotable nullability flexible types

### ISSUE THREAD

**Issue by dnpetrov** [Kotlin/KEEP#82]
https://github.com/Kotlin/KEEP/blob/master/proposals/denotable-nullability-flexible-types.md

**Comment by ilya-g** [comment]
Consider an alternative for collection classes implementation use case: non-checking unsafe conversion from `T?` to `T`, like `unsafeCast` function in JS. 
So you declare a storage array with uninitialized elements as `Container<T?>` and after extracting an initialized element from that storage you can make an unsafeCast to the desired nullability.
Also, since collections are often generic with unconstrained type parameters, the cast from T? to T is therefore unchecked anyway.

Could you add some examples showing how denotable flexible types are better than lateinit in case of objects with complex lifecycle?

**Comment by dnpetrov** [comment]
`unsafeCast` is a good idea.

> Could you add some examples showing how denotable flexible types are better than lateinit in case of objects with complex lifecycle?

For example, some pre-JMH benchmarks are organized like this:
1. Create a benchmarking "atom"
2. In a loop:
2.1. Initialize "atom"
2.2. Do some benchmarking
2.3. Reset "atom"

Straight-forward conversion from Java to Kotlin introduces lateinit properties, which impose additional (implicit) null checks in tight loops.

**Comment by ilya-g** [comment]
Related proposal about `unsafeCast`: https://youtrack.jetbrains.com/issue/KT-20483

**Comment by nickallendev** [comment]
Properties that will be initialized through reflection could benefit from this: https://discuss.kotlinlang.org/t/non-null-val-initialization-alternative-to-lateinit-delegates-notnull/12732

**Comment by elizarov** [comment]
Having discussed this with the Kotlin team we've decided that we don't want to carry nullability flexible types (`T!`) into the Kotlin type-system. Essentially, nullability-flexible types represent an unsound loophole in an otherwise sound Kotlin system and complicate the Kotlin type-system quite a lot. Kotlin flexible types are limited to the direct interaction with less-typed Java code and this limitation is a feature, not a bug. It requires dealing with the incoming platform types right away, limiting their proliferation throughout the code. 

The considerable help in making this decision was provided by the Swift language's experience with "implicitly unwrapped optional types" that coincidentally also use `T!` syntax. This post on [The Problem with Implicitly Unwrapped Optionals](https://metova.com/the-problem-with-implicitly-unwrapped-optionals/) puts it this way:

> Swift optionals, when used correctly, are a very powerful tool. When used incorrectly, they lead to one of the most common Swift crashes on Stack Overflow. When it comes to the correct usage of optionals, implicitly unwrapped optionals always get it wrong. There are two circumstances in Swift in which we deal with implicitly unwrapped optionals: @IBOutlets and interoperating with Objective-C code, which has not properly added nullability annotations. Outside of these two exceptions, we should avoid implicitly unwrapped optionals.

There are some more direct answers, for example in [When Should You Use Implicitly Unwrapped Optionals](https://cocoacasts.com/when-should-you-use-implicitly-unwrapped-optionals) the answer is:

> The short answer to this question is "Never."

This KEEP had identified two primary use-cases for denotable nullability flexible types.

**Use-case 1** 

> Collection classes implementation in pure Kotlin. Collections that pre-allocate arrays with extra elements for internal storage rely on extra invariants for null safety.

Having looked at some code examples, we have not found that nullability flexible types somehow improve the soundness or type-safety for collection implementations. 

**Use-case 2** 

> Objects with complex lifecycle, such as GUI elements or unit tests, rely on particular sequence of method invocations.

In Kotlin, this use-case is already covered by the direct cousins of flexible types &mdash; `lateinit var` declarations. As already discussed, the fact that they cannot be easily (with a succinct syntax) expressed as a type is a feature, not a bug. Other key limitations of `lateinit` variables that were identified in this KEEP are tracked in a separate issue: [KT-15284](https://youtrack.jetbrains.com/issue/KT-15284) Implement lateinit for nullable and primitive types.

**Comment by lukaseder** [comment]
I'd like to share a use-case for this feature that I currently don't see how to model otherwise. I've also described it here: https://github.com/jOOQ/jOOQ/issues/12949#issuecomment-1023272786

[jOOQ](https://www.jooq.org) is an internal DSL modelling SQL in Java (and kotlin, scala). It ships with a code generator that models the SQL schema as Java / kotlin / scala object hierarchies. A table has a set of `Field<T>` members describing columns, where `T` corresponds to the column type.

One may be tempted to think that, given:

```sql
create table t (i int not null, j int);
```

The above should produce column definitions of the types:

```kotlin
val i: Field<Int> = ...
val j: Field<Int?> = ...
```

But this isn't correct, as there are numerous possible SQL queries where a reference to `T.I` becomes nullable without any type checker being aware of this. For example:

```sql
-- Anything outer joined can be NULL again
select t.i from x left join t on p

-- Empty scalar subqueries always produce NULL
select (select t.i from t where false)

-- No one thinks of this case, but yes, T.I is null in this query
select t.i from t where false group by grouping sets ((t), ())
```

So, `Field<Int>` is often wrong, `Field<Int?>` is always correct, but produces cumbersome client code, whereas  `Field<Int!>` is a pragmatic escape hatch. In a lot of cases, it's not really easy to prove whether a resulting value is nullable or not.

Now, such internal DSLs are definitely a niche topic for a general purpose language like kotlin. If a DSL doesn't force itself to model an external DSL, it can probably be designed in a way to avoid this particular problem, because the difficulties stem from the SQL language itself.

I just wanted to share another use-case that doesn't fit the other 2 use-cases listed here: https://github.com/Kotlin/KEEP/issues/82#issuecomment-751210358

**Comment by elizarov** [comment]
@lukaseder Thanks a lot for the use case. It does seem very interesting but, unfortunately, it does not invalidate our original design rationale for rejecting denotable nullability flexible types per se. We know that simply adding `T!` types to the language is not going to end up well.

If we want to add `T!` types, then we have to figure out some way to contain them to the "good places" and that is how use-cases, like yours, help us. Hopefully, by collecting those use-cases, we'll be able to eventually figure out a comprehensive set of restrictions on `T!` types that will make them useful, but without introducing too much error-proneness into the language.
